spring:
  datasource:
    url: jdbc:postgresql://ep-small-flower-092994.us-east-2.aws.neon.tech/neondb?userkradhenz&password=hBR07cAvMUbr
    username: kradhenz
    password: hBR07cAvMUbr
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
server:
  port: 8083
